import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Header from "@/components/Header";
import HeaderMobile from "@/components/HeaderMobile";
import SessionGuard from "@/components/SessionGuard";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white ${inter.className}`}>
        <Providers>
          <SessionGuard>
            <div className="flex">
              <Sidebar />
              <main className="flex-1">
                <div className="flex flex-col md:ml-60 sm:border-r sm:border-zinc-700 min-h-screen">
                  <Header />
                  <HeaderMobile />
                  <div className="flex flex-col pt-2 px-4 space-y-2 bg-zinc-100 flex-grow pb-4">
                    {children}
                  </div>
                </div>
              </main>
            </div>
          </SessionGuard>
        </Providers>
      </body>
    </html>
  );
}
