version: '3.8'
services:
  keycloak:
    container_name: keycloak-2
    image: quay.io/keycloak/keycloak:23.0.7
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: <password>
    ports:
      - "8080:8080"
    command: "start-dev"
    volumes:
      - .local/keycloak/:/opt/keycloak/data/
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: <password>
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: <password>
      ME_CONFIG_MONGODB_URL: mongodb://root:<password>@mongo:27017/
      ME_CONFIG_BASICAUTH: false