spring:
  application:
    name: cert-manager
  data:
    mongodb:
      uri: mongodb://root:<password>@localhost:27017/
      database: cert-manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cert-manager
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: cert-manager-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081
  servlet:
    context-path: /cert-manager

cert-manager:
  data-encryption:
    keystore: file:.local/cert-manager.p12
    password: <password>
    alias: cert-manager-key

